// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// barycenter.cpp
writable::list barycenter_parallel_cpp(const doubles_matrix<>& A, const doubles_matrix<>& C, const doubles_matrix<>& w, double reg, bool withjac, int maxiter, double zerotol);
extern "C" SEXP _wig_barycenter_parallel_cpp(SEXP A, SEXP C, SEXP w, SEXP reg, SEXP withjac, SEXP maxiter, SEXP zerotol) {
  BEGIN_CPP11
    return cpp11::as_sexp(barycenter_parallel_cpp(cpp11::as_cpp<cpp11::decay_t<const doubles_matrix<>&>>(A), cpp11::as_cpp<cpp11::decay_t<const doubles_matrix<>&>>(C), cpp11::as_cpp<cpp11::decay_t<const doubles_matrix<>&>>(w), cpp11::as_cpp<cpp11::decay_t<double>>(reg), cpp11::as_cpp<cpp11::decay_t<bool>>(withjac), cpp11::as_cpp<cpp11::decay_t<int>>(maxiter), cpp11::as_cpp<cpp11::decay_t<double>>(zerotol)));
  END_CPP11
}
// barycenter.cpp
writable::list barycenter_log_cpp(const doubles_matrix<>& A, const doubles_matrix<>& C, const doubles_matrix<>& w, double reg, bool withjac, int maxiter, double zerotol);
extern "C" SEXP _wig_barycenter_log_cpp(SEXP A, SEXP C, SEXP w, SEXP reg, SEXP withjac, SEXP maxiter, SEXP zerotol) {
  BEGIN_CPP11
    return cpp11::as_sexp(barycenter_log_cpp(cpp11::as_cpp<cpp11::decay_t<const doubles_matrix<>&>>(A), cpp11::as_cpp<cpp11::decay_t<const doubles_matrix<>&>>(C), cpp11::as_cpp<cpp11::decay_t<const doubles_matrix<>&>>(w), cpp11::as_cpp<cpp11::decay_t<double>>(reg), cpp11::as_cpp<cpp11::decay_t<bool>>(withjac), cpp11::as_cpp<cpp11::decay_t<int>>(maxiter), cpp11::as_cpp<cpp11::decay_t<double>>(zerotol)));
  END_CPP11
}
// sinkhorn.cpp
writable::list sinkhorn_vanilla_cpp(const doubles_matrix<>& a, const doubles_matrix<>& b, const doubles_matrix<>& C, double reg, bool withgrad, int maxiter, double zerotol);
extern "C" SEXP _wig_sinkhorn_vanilla_cpp(SEXP a, SEXP b, SEXP C, SEXP reg, SEXP withgrad, SEXP maxiter, SEXP zerotol) {
  BEGIN_CPP11
    return cpp11::as_sexp(sinkhorn_vanilla_cpp(cpp11::as_cpp<cpp11::decay_t<const doubles_matrix<>&>>(a), cpp11::as_cpp<cpp11::decay_t<const doubles_matrix<>&>>(b), cpp11::as_cpp<cpp11::decay_t<const doubles_matrix<>&>>(C), cpp11::as_cpp<cpp11::decay_t<double>>(reg), cpp11::as_cpp<cpp11::decay_t<bool>>(withgrad), cpp11::as_cpp<cpp11::decay_t<int>>(maxiter), cpp11::as_cpp<cpp11::decay_t<double>>(zerotol)));
  END_CPP11
}
// sinkhorn.cpp
writable::list sinkhorn_log_cpp(const doubles_matrix<>& a, const doubles_matrix<>& b, const doubles_matrix<>& C, double reg, bool withgrad, int maxiter, double zerotol);
extern "C" SEXP _wig_sinkhorn_log_cpp(SEXP a, SEXP b, SEXP C, SEXP reg, SEXP withgrad, SEXP maxiter, SEXP zerotol) {
  BEGIN_CPP11
    return cpp11::as_sexp(sinkhorn_log_cpp(cpp11::as_cpp<cpp11::decay_t<const doubles_matrix<>&>>(a), cpp11::as_cpp<cpp11::decay_t<const doubles_matrix<>&>>(b), cpp11::as_cpp<cpp11::decay_t<const doubles_matrix<>&>>(C), cpp11::as_cpp<cpp11::decay_t<double>>(reg), cpp11::as_cpp<cpp11::decay_t<bool>>(withgrad), cpp11::as_cpp<cpp11::decay_t<int>>(maxiter), cpp11::as_cpp<cpp11::decay_t<double>>(zerotol)));
  END_CPP11
}
// tsvd.cpp
cpp11::doubles_matrix<> tsvd_cpp(const doubles_matrix<>& MR, const int k, const int flip_sign);
extern "C" SEXP _wig_tsvd_cpp(SEXP MR, SEXP k, SEXP flip_sign) {
  BEGIN_CPP11
    return cpp11::as_sexp(tsvd_cpp(cpp11::as_cpp<cpp11::decay_t<const doubles_matrix<>&>>(MR), cpp11::as_cpp<cpp11::decay_t<const int>>(k), cpp11::as_cpp<cpp11::decay_t<const int>>(flip_sign)));
  END_CPP11
}
// utils.cpp
cpp11::doubles_matrix<> euclidean_cpp(const doubles_matrix<>& AR);
extern "C" SEXP _wig_euclidean_cpp(SEXP AR) {
  BEGIN_CPP11
    return cpp11::as_sexp(euclidean_cpp(cpp11::as_cpp<cpp11::decay_t<const doubles_matrix<>&>>(AR)));
  END_CPP11
}
// utils.cpp
cpp11::doubles_matrix<> doc2dist_cpp(cpp11::list docs, cpp11::strings dict);
extern "C" SEXP _wig_doc2dist_cpp(SEXP docs, SEXP dict) {
  BEGIN_CPP11
    return cpp11::as_sexp(doc2dist_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(docs), cpp11::as_cpp<cpp11::decay_t<cpp11::strings>>(dict)));
  END_CPP11
}
// wdl.cpp
writable::list wdl_cpp(const doubles_matrix<>& YR, const doubles_matrix<>& CR, const double reg, const int S, const int batch_size, const int epochs, int sinkhorn_mode, const int max_iter, const double zero_tol, const int optimizer, const double eta, const double gamma, const double beta1, const double beta2, const double eps, const int rng_seed, const bool verbose);
extern "C" SEXP _wig_wdl_cpp(SEXP YR, SEXP CR, SEXP reg, SEXP S, SEXP batch_size, SEXP epochs, SEXP sinkhorn_mode, SEXP max_iter, SEXP zero_tol, SEXP optimizer, SEXP eta, SEXP gamma, SEXP beta1, SEXP beta2, SEXP eps, SEXP rng_seed, SEXP verbose) {
  BEGIN_CPP11
    return cpp11::as_sexp(wdl_cpp(cpp11::as_cpp<cpp11::decay_t<const doubles_matrix<>&>>(YR), cpp11::as_cpp<cpp11::decay_t<const doubles_matrix<>&>>(CR), cpp11::as_cpp<cpp11::decay_t<const double>>(reg), cpp11::as_cpp<cpp11::decay_t<const int>>(S), cpp11::as_cpp<cpp11::decay_t<const int>>(batch_size), cpp11::as_cpp<cpp11::decay_t<const int>>(epochs), cpp11::as_cpp<cpp11::decay_t<int>>(sinkhorn_mode), cpp11::as_cpp<cpp11::decay_t<const int>>(max_iter), cpp11::as_cpp<cpp11::decay_t<const double>>(zero_tol), cpp11::as_cpp<cpp11::decay_t<const int>>(optimizer), cpp11::as_cpp<cpp11::decay_t<const double>>(eta), cpp11::as_cpp<cpp11::decay_t<const double>>(gamma), cpp11::as_cpp<cpp11::decay_t<const double>>(beta1), cpp11::as_cpp<cpp11::decay_t<const double>>(beta2), cpp11::as_cpp<cpp11::decay_t<const double>>(eps), cpp11::as_cpp<cpp11::decay_t<const int>>(rng_seed), cpp11::as_cpp<cpp11::decay_t<const bool>>(verbose)));
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_wig_barycenter_log_cpp",      (DL_FUNC) &_wig_barycenter_log_cpp,       7},
    {"_wig_barycenter_parallel_cpp", (DL_FUNC) &_wig_barycenter_parallel_cpp,  7},
    {"_wig_doc2dist_cpp",            (DL_FUNC) &_wig_doc2dist_cpp,             2},
    {"_wig_euclidean_cpp",           (DL_FUNC) &_wig_euclidean_cpp,            1},
    {"_wig_sinkhorn_log_cpp",        (DL_FUNC) &_wig_sinkhorn_log_cpp,         7},
    {"_wig_sinkhorn_vanilla_cpp",    (DL_FUNC) &_wig_sinkhorn_vanilla_cpp,     7},
    {"_wig_tsvd_cpp",                (DL_FUNC) &_wig_tsvd_cpp,                 3},
    {"_wig_wdl_cpp",                 (DL_FUNC) &_wig_wdl_cpp,                 17},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_wig(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
