// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// barycenter_parallel_cpp
Rcpp::List barycenter_parallel_cpp(const SEXP& A, const SEXP& C, const SEXP& w, double reg, const SEXP& b_ext, bool withgrad, bool usecuda, int maxiter, double zerotol, int verbose);
RcppExport SEXP _rwig_barycenter_parallel_cpp(SEXP ASEXP, SEXP CSEXP, SEXP wSEXP, SEXP regSEXP, SEXP b_extSEXP, SEXP withgradSEXP, SEXP usecudaSEXP, SEXP maxiterSEXP, SEXP zerotolSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const SEXP& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const SEXP& >::type C(CSEXP);
    Rcpp::traits::input_parameter< const SEXP& >::type w(wSEXP);
    Rcpp::traits::input_parameter< double >::type reg(regSEXP);
    Rcpp::traits::input_parameter< const SEXP& >::type b_ext(b_extSEXP);
    Rcpp::traits::input_parameter< bool >::type withgrad(withgradSEXP);
    Rcpp::traits::input_parameter< bool >::type usecuda(usecudaSEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< double >::type zerotol(zerotolSEXP);
    Rcpp::traits::input_parameter< int >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(barycenter_parallel_cpp(A, C, w, reg, b_ext, withgrad, usecuda, maxiter, zerotol, verbose));
    return rcpp_result_gen;
END_RCPP
}
// barycenter_log_cpp
Rcpp::List barycenter_log_cpp(const arma::mat& A, const arma::mat& C, const arma::vec& w, double reg, const arma::vec& b_ext, bool withgrad, const int& n_threads, int maxiter, double zerotol, int verbose);
RcppExport SEXP _rwig_barycenter_log_cpp(SEXP ASEXP, SEXP CSEXP, SEXP wSEXP, SEXP regSEXP, SEXP b_extSEXP, SEXP withgradSEXP, SEXP n_threadsSEXP, SEXP maxiterSEXP, SEXP zerotolSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type C(CSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type w(wSEXP);
    Rcpp::traits::input_parameter< double >::type reg(regSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type b_ext(b_extSEXP);
    Rcpp::traits::input_parameter< bool >::type withgrad(withgradSEXP);
    Rcpp::traits::input_parameter< const int& >::type n_threads(n_threadsSEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< double >::type zerotol(zerotolSEXP);
    Rcpp::traits::input_parameter< int >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(barycenter_log_cpp(A, C, w, reg, b_ext, withgrad, n_threads, maxiter, zerotol, verbose));
    return rcpp_result_gen;
END_RCPP
}
// cuda_available_cpp
bool cuda_available_cpp();
RcppExport SEXP _rwig_cuda_available_cpp() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(cuda_available_cpp());
    return rcpp_result_gen;
END_RCPP
}
// sinkhorn_vanilla_cpp
Rcpp::List sinkhorn_vanilla_cpp(const SEXP& a, const SEXP& b, const SEXP& C, double reg, bool withgrad, bool usecuda, int maxiter, double zerotol, int verbose);
RcppExport SEXP _rwig_sinkhorn_vanilla_cpp(SEXP aSEXP, SEXP bSEXP, SEXP CSEXP, SEXP regSEXP, SEXP withgradSEXP, SEXP usecudaSEXP, SEXP maxiterSEXP, SEXP zerotolSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const SEXP& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const SEXP& >::type b(bSEXP);
    Rcpp::traits::input_parameter< const SEXP& >::type C(CSEXP);
    Rcpp::traits::input_parameter< double >::type reg(regSEXP);
    Rcpp::traits::input_parameter< bool >::type withgrad(withgradSEXP);
    Rcpp::traits::input_parameter< bool >::type usecuda(usecudaSEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< double >::type zerotol(zerotolSEXP);
    Rcpp::traits::input_parameter< int >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(sinkhorn_vanilla_cpp(a, b, C, reg, withgrad, usecuda, maxiter, zerotol, verbose));
    return rcpp_result_gen;
END_RCPP
}
// sinkhorn_log_cpp
Rcpp::List sinkhorn_log_cpp(const arma::vec& a, const arma::vec& b, const arma::mat& C, double reg, bool withgrad, const int& n_threads, int maxiter, double zerotol, int verbose);
RcppExport SEXP _rwig_sinkhorn_log_cpp(SEXP aSEXP, SEXP bSEXP, SEXP CSEXP, SEXP regSEXP, SEXP withgradSEXP, SEXP n_threadsSEXP, SEXP maxiterSEXP, SEXP zerotolSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type b(bSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type C(CSEXP);
    Rcpp::traits::input_parameter< double >::type reg(regSEXP);
    Rcpp::traits::input_parameter< bool >::type withgrad(withgradSEXP);
    Rcpp::traits::input_parameter< const int& >::type n_threads(n_threadsSEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< double >::type zerotol(zerotolSEXP);
    Rcpp::traits::input_parameter< int >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(sinkhorn_log_cpp(a, b, C, reg, withgrad, n_threads, maxiter, zerotol, verbose));
    return rcpp_result_gen;
END_RCPP
}
// tsvd_cpp
arma::mat tsvd_cpp(const arma::mat& M, const int k, const int flip_sign);
RcppExport SEXP _rwig_tsvd_cpp(SEXP MSEXP, SEXP kSEXP, SEXP flip_signSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type M(MSEXP);
    Rcpp::traits::input_parameter< const int >::type k(kSEXP);
    Rcpp::traits::input_parameter< const int >::type flip_sign(flip_signSEXP);
    rcpp_result_gen = Rcpp::wrap(tsvd_cpp(M, k, flip_sign));
    return rcpp_result_gen;
END_RCPP
}
// euclidean_cpp
arma::mat euclidean_cpp(const arma::mat& A);
RcppExport SEXP _rwig_euclidean_cpp(SEXP ASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type A(ASEXP);
    rcpp_result_gen = Rcpp::wrap(euclidean_cpp(A));
    return rcpp_result_gen;
END_RCPP
}
// doc2dist_cpp
arma::mat doc2dist_cpp(Rcpp::List docs, Rcpp::CharacterVector dict);
RcppExport SEXP _rwig_doc2dist_cpp(SEXP docsSEXP, SEXP dictSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type docs(docsSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type dict(dictSEXP);
    rcpp_result_gen = Rcpp::wrap(doc2dist_cpp(docs, dict));
    return rcpp_result_gen;
END_RCPP
}
// wdl_cpp
Rcpp::List wdl_cpp(const SEXP& Y, const SEXP& C, const double reg, const int S, const int n_threads, const int batch_size, const int epochs, int sinkhorn_mode, bool usecuda, const int max_iter, const double zero_tol, const int optimizer, const double eta, const double gamma, const double beta1, const double beta2, const double eps, const bool verbose);
RcppExport SEXP _rwig_wdl_cpp(SEXP YSEXP, SEXP CSEXP, SEXP regSEXP, SEXP SSEXP, SEXP n_threadsSEXP, SEXP batch_sizeSEXP, SEXP epochsSEXP, SEXP sinkhorn_modeSEXP, SEXP usecudaSEXP, SEXP max_iterSEXP, SEXP zero_tolSEXP, SEXP optimizerSEXP, SEXP etaSEXP, SEXP gammaSEXP, SEXP beta1SEXP, SEXP beta2SEXP, SEXP epsSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const SEXP& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const SEXP& >::type C(CSEXP);
    Rcpp::traits::input_parameter< const double >::type reg(regSEXP);
    Rcpp::traits::input_parameter< const int >::type S(SSEXP);
    Rcpp::traits::input_parameter< const int >::type n_threads(n_threadsSEXP);
    Rcpp::traits::input_parameter< const int >::type batch_size(batch_sizeSEXP);
    Rcpp::traits::input_parameter< const int >::type epochs(epochsSEXP);
    Rcpp::traits::input_parameter< int >::type sinkhorn_mode(sinkhorn_modeSEXP);
    Rcpp::traits::input_parameter< bool >::type usecuda(usecudaSEXP);
    Rcpp::traits::input_parameter< const int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< const double >::type zero_tol(zero_tolSEXP);
    Rcpp::traits::input_parameter< const int >::type optimizer(optimizerSEXP);
    Rcpp::traits::input_parameter< const double >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< const double >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< const double >::type beta1(beta1SEXP);
    Rcpp::traits::input_parameter< const double >::type beta2(beta2SEXP);
    Rcpp::traits::input_parameter< const double >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< const bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(wdl_cpp(Y, C, reg, S, n_threads, batch_size, epochs, sinkhorn_mode, usecuda, max_iter, zero_tol, optimizer, eta, gamma, beta1, beta2, eps, verbose));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rwig_barycenter_parallel_cpp", (DL_FUNC) &_rwig_barycenter_parallel_cpp, 10},
    {"_rwig_barycenter_log_cpp", (DL_FUNC) &_rwig_barycenter_log_cpp, 10},
    {"_rwig_cuda_available_cpp", (DL_FUNC) &_rwig_cuda_available_cpp, 0},
    {"_rwig_sinkhorn_vanilla_cpp", (DL_FUNC) &_rwig_sinkhorn_vanilla_cpp, 9},
    {"_rwig_sinkhorn_log_cpp", (DL_FUNC) &_rwig_sinkhorn_log_cpp, 9},
    {"_rwig_tsvd_cpp", (DL_FUNC) &_rwig_tsvd_cpp, 3},
    {"_rwig_euclidean_cpp", (DL_FUNC) &_rwig_euclidean_cpp, 1},
    {"_rwig_doc2dist_cpp", (DL_FUNC) &_rwig_doc2dist_cpp, 2},
    {"_rwig_wdl_cpp", (DL_FUNC) &_rwig_wdl_cpp, 18},
    {NULL, NULL, 0}
};

RcppExport void R_init_rwig(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
