# Generated by cpp11: do not edit by hand

barycenter_parallel_cpp <- function(A, C, w, reg, withjac, maxiter, zerotol) {
  .Call(`_wig_barycenter_parallel_cpp`, A, C, w, reg, withjac, maxiter, zerotol)
}

barycenter_log_cpp <- function(A, C, w, reg, withjac, maxiter, zerotol) {
  .Call(`_wig_barycenter_log_cpp`, A, C, w, reg, withjac, maxiter, zerotol)
}

sinkhorn_vanilla_cpp <- function(a, b, C, reg, withgrad, maxiter, zerotol) {
  .Call(`_wig_sinkhorn_vanilla_cpp`, a, b, C, reg, withgrad, maxiter, zerotol)
}

sinkhorn_log_cpp <- function(a, b, C, reg, withgrad, maxiter, zerotol) {
  .Call(`_wig_sinkhorn_log_cpp`, a, b, C, reg, withgrad, maxiter, zerotol)
}

tsvd_cpp <- function(MR, k, flip_sign) {
  .Call(`_wig_tsvd_cpp`, MR, k, flip_sign)
}

euclidean_cpp <- function(AR) {
  .Call(`_wig_euclidean_cpp`, AR)
}

doc2dist_cpp <- function(docs, dict) {
  .Call(`_wig_doc2dist_cpp`, docs, dict)
}

wdl_cpp <- function(YR, CR, reg, S, batch_size, epochs, sinkhorn_mode, max_iter, zero_tol, optimizer, eta, gamma, beta1, beta2, eps, rng_seed, verbose) {
  .Call(`_wig_wdl_cpp`, YR, CR, reg, S, batch_size, epochs, sinkhorn_mode, max_iter, zero_tol, optimizer, eta, gamma, beta1, beta2, eps, rng_seed, verbose)
}
